name: bloc_example
description: BLOc example awaik

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.4
  flutter:
    sdk: flutter
  http: ^0.13.4
  rxdart: ^0.27.3


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true